services:
  proyecto_fast_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyecto_fast_api
    volumes:
      - ./main:/data/code/
    ports:
      - "1998:1998"
    command: /bin/bash -c "source entornoVirtual/bin/activate && cd code/ && ls && uvicorn core.main:app --reload --host 0.0.0.0 --port 1998"
